package com.springboot.major_project.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import org.springframework.core.io.FileSystemResource;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

@Service
@RequiredArgsConstructor
public class EmailService {

    private final PdfService pdfService;
    private final JavaMailSender sender;

    @Async
    public void sendMail() throws IOException, MessagingException {


        MimeMessage mimeMessage = sender.createMimeMessage();
        MimeMessageHelper messageHelper = new MimeMessageHelper(mimeMessage,true);
        messageHelper.setTo("junaidkhatri102@gmail.com");
        messageHelper.setFrom("junaidkhatri102@gmail.com");
        messageHelper.setSubject("Pdf file");
        mimeMessage.setText("This pdf is autogenerated");

        String pdfPath = pdfService.pdfGenerator();
        File file = new File(pdfPath);

        FileSystemResource fileResource = new FileSystemResource(file);
        messageHelper.addAttachment("report.pdf", fileResource);

        sender.send(mimeMessage);
    }

}
